n = str(input('Digite seu nome completo: ')).strip()
nome = n.split()
print('Prazer em te conhecer, {}! Seja muito bem-vindo(a)!'.format(n))
print('O seu primeiro nome é {}.'.format(nome[0]))
print('O seu último nome é {}.'.format(nome[len(nome)-1]))