times = ("Flamengo", "Palmeiras", "Atlético Paranaense", "Fluminense", "Bahia", "Cruzeiro", "Atlético-MG", "Santos", "Coritiba", "RB Bragantino", "São Paulo", "Botafogo", "Vitória", "Corinthians", "Mirassol", "Vasco DA Gama", "Internacional", "Remo", "Chapecoense")
print(f"Lista de Times do Brasileirão: {times}")
print("=-" * 30)
print(f"Os primeiros 5 times da tabela são: {times[0:5]}")
print("=-" * 30)
print(f"Os últimos 4 colocados da tabela são: {times[-4:]}")
print("=-" * 30)
print(f"Time em Ordem Alfabética: {sorted(times)}")
print("=-" * 30)
print(f"O Chapecoense está na {times.index('Chapecoense')}ª posição")